apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: base
  namespace: kargo-demo
spec:
  subscriptions:
  - git:
      branch: main
      commitSelectionStrategy: NewestFromBranch
      discoveryLimit: 20
      repoURL: https://github.com/reikamoon/eks-tutorial.git
      includePaths:
      - base/values.yaml