apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: features
  namespace: kargo-helm
spec:
  shard: kargo-agent
  subscriptions:
  - git:
      branch: main
      commitSelectionStrategy: NewestFromBranch
      discoveryLimit: 20
      repoURL: https://github.com/reikamoon/eks-tutorial.git
      includePaths:
      - base/feature-flags.yaml
