apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-prd
  namespace: argocd
  annotations:
    kargo.akuity.io/authorized-stage: kargo-demo:prd
spec:
  project: demo
  source:
    repoURL: 'https://github.com/reikamoon/eks-tutorial'
    path: guestbook
    targetRevision: HEAD
    helm:
      valueFiles:
        - values-prd.yaml
  destination:
    namespace: guestbook-prd
    name: anjelica-test
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
