apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-dev
  namespace: argocd
  annotations:
    kargo.akuity.io/authorized-stage: kargo-helm:dev
spec:
  project: default
  source:
    repoURL: 'https://github.com/reikamoon/eks-tutorial'
    path: guestbook
    targetRevision: HEAD
    helm:
      valueFiles:
        - values-dev.yaml
  destination:
    namespace: guestbook-dev
    name: eks
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
