apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-stg
  namespace: argocd
  annotations:
    kargo.akuity.io/authorized-stage: kargo-demo:stg
spec:
  project: demo
  source:
    repoURL: 'https://github.com/reikamoon/eks-tutorial'
    path: guestbook
    targetRevision: HEAD
    helm:
      valueFiles:
        - values-stg.yaml
  destination:
    namespace: guestbook-stg
    name: eks
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
