apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo-apps
spec:
  project: default
  source:
    repoURL: https://github.com/reikamoon/eks-tutorial.git
    path: kargo
  destination:
    name: eks-workshop
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
