apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo-guestbook
spec:
  project: default
  source:
    repoURL: https://github.com/reikamoon/eks-tutorial.git
    path: kargo
  destination:
    server: https://cluster-kargo:6445
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
