apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portal
  namespace: argocd
spec:
  project: demo
  source:
    repoURL: 'https://github.com/reikamoon/eks-tutorial'
    path: portal
    targetRevision: HEAD
  destination:
    namespace: portal
    name: eks
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
